spring:
  rabbitmq:
    host: 192.168.31.62
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123
      url:  jdbc:mysql://192.168.31.62:3306/spring_cloud_sell?characterEncoding=utf8&userSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 18087
env:
  test
label:
  release
