eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
label: release
server:
  port: 18088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://192.168.31.62:3306/spring_cloud_sell?characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.31.62
  redis:
    host: 192.168.31.62
    port: 6379
